### ISSUE TITLE
Editor fails to load banks due to localized audio tables

### ISSUE THREAD

**Issue by MadFlyFish** [alessandrofama/fmod-for-godot#1] opened 2023-03-11 13:23 UTC
It seems that the bank path setting is all right but still fails to load the banks

system: window 11 pro
version: godot 4.0 stable

![image](https://user-images.githubusercontent.com/36298330/224487050-a0ce5081-2879-4138-a6f9-856c581f94fd.png)
![image](https://user-images.githubusercontent.com/36298330/224487082-04588ad9-cf1f-454d-88ab-1f613c24718d.png)
![image](https://user-images.githubusercontent.com/36298330/224487110-5fb895c5-9b0f-48fa-bfc4-45e9f50e1531.png)

**Comment by alessandrofama** [comment] 2023-03-11 17:01
I can check this on Monday. 
Is there any way you could share your project with me? That would make it easier to debug. Thank you!
I can see the warning ``Property not found: [...]`` which means there is something wrong with the project settings.

**Comment by EXSPIRAVIT1104OFFICIAL** [comment] 2023-03-13 13:41
> 

I tried to edit the build path on FMOD studio and build the banks, and the path is changed, and although that changed path exists, the banks can't be loaded. But if you restart the project in Godot after saving the changed project settings, the changes made to the bank path and the folder structure would not lead to the fail shown on loading banks.

你这个问题因该是改了bank path，点了refresh project没成功差不多的原因。我刚刚也遇到了；改完project setting重启一下，再refresh project就可以了。

**Comment by MadFlyFish** [comment] 2023-03-13 15:16
> > 
> 
> I tried to edit the build path on FMOD studio and build the banks, and the path is changed, and although that changed path exists, the banks can't be loaded. But if you restart the project in Godot after saving the changed project settings, the changes made to the bank path and the folder structure would not lead to the fail shown on loading banks.
> 
> 你这个问题因该是改了bank path，点了refresh project没成功差不多的原因。我刚刚也遇到了；改完project setting重启一下，再refresh project就可以了。

Thanks. I will keep an eye on that use case and see if I can reproduce.

**Comment by surfacedfox** [comment] 2023-03-14 22:04
Issue continues, but without the aforementioned `Property not found` warning. Console readout:  
`[FMOD] Saved Project Settings
WARNING: [FMOD] Failed to get icon: 0
     at: push_warning (core/variant/variant_utility.cpp:914)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
[FMOD] Initialized Editor System
[FMOD] Loading Editor Banks
WARNING: [FMOD] Failed to load editor banks. Please verify that the banks path location in the Project Settings is correct. Refresh the project afterwards.
     at: push_warning (core/variant/variant_utility.cpp:914)`

**Comment by alessandrofama** [comment] 2023-03-14 22:19
How do your banks look like?
Do you use localized audio tables/banks by chance?
If yes, can you try to remove the localized versions of your banks and try to load the project again? Might be an issue with that as I haven't been able to reproduce this issue yet.

**Comment by surfacedfox** [comment] 2023-03-14 22:54
Nope, I don't use localised audio tables or banks. My test project has one single event.
![image](https://user-images.githubusercontent.com/115193899/225159833-c8760125-a782-452d-9006-512f157fa678.png)

**Comment by surfacedfox** [comment] 2023-03-14 23:09
Alright, for me it was the fact that I was using plugins. Using the built-in spatializer fixed it.

**Comment by alessandrofama** [comment] 2023-04-14 18:12
I haven’t worked on a solution yet, but I can reproduce the problem so it should be fixable. The only workaround right now is avoiding using localized audio tables. The demo project that ships with FMOD Studio unfortunately won‘t work due to this unless you delete the additional localized dialogue banks.

**Comment by alessandrofama** [comment] 2023-08-19 00:46
This should be fixed by https://github.com/alessandrofama/fmod-for-godot/pull/13.

**Closed by alessandrofama** 2023-08-19 00:46 UTC
Labels: bug
